services:
  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --create --topic stats.user-actions.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic stats.events-similarity.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
    init: true
    
  discovery-server:
    build: ./infra/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-server:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build: ./infra/config-server
    container_name: config-server
    ports:
      - "8181:8181"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.prefer-ip-address=true
      - server.port=8181
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:8181/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  gateway-server:
    build: ./infra/gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.prefer-ip-address=true
      - server.port=8080

  user-service:
    build: ./core/user-service
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb?currentSchema=user_service
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.prefer-ip-address=true
      - server.port=8082

  event-service:
    build: ./core/event-service
    container_name: event-service
    ports:
      - "8083:8083"
    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb?currentSchema=event_service
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.prefer-ip-address=true
      - server.port=8083

  request-service:
    build: ./core/request-service
    container_name: request-service
    ports:
      - "8084:8084"
    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb?currentSchema=request_service
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.prefer-ip-address=true
      - server.port=8084

  comment-service:
    build: ./core/comment-service
    container_name: comment-service
    ports:
      - "8085:8085"
    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb?currentSchema=comment_service
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.prefer-ip-address=true
      - server.port=8085

  stats-server:
    build: ./stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
      - eureka.instance.hostname=stats-server
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://stats-server:9090/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 10
