stats:
  kafka:
    bootstrap-servers: localhost:9092
    user-actions-topic: stats.user-actions.v1

logging:
  level:
    org.springframework.web: INFO
    org.springframework.validation: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

server:
  port: 0
  shutdown: graceful
grpc:
  server:
    port: 0