stats:
  kafka:
    bootstrap-servers: localhost:9092
    user-actions-topic: stats.user-actions.v1
    events-similarity-topic: stats.events-similarity.v1
    group-id: aggregator-consumer-group
    auto-offset-reset: latest
    enable-auto-commit: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

server:
  port: 0
  shutdown: graceful