spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # Event Routes → EVENT-SERVICE
        - id: event_admin_route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/admin/events/**

        - id: event_user_route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/users/*/events/**

        - id: event_public_route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**

        # Category Routes → EVENT-SERVICE
        - id: category_admin_route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/admin/categories/**

        - id: category_public_route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/categories/**

        # Compilation Routes → EVENT-SERVICE
        - id: compilation_admin_route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/admin/compilations/**

        - id: compilation_public_route
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/compilations/**

        # User Routes → USER-SERVICE
        - id: user_admin_route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/admin/users,/admin/users/**

        # Request Routes → REQUEST-SERVICE
        - id: request_user_route
          uri: lb://REQUEST-SERVICE
          predicates:
            - Path=/users/*/requests/**

        # Comment Routes → COMMENT-SERVICE
        - id: comment_admin_route
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/admin/comments/**

        - id: comment_private_route
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/users/*/comments/**

        # Stats Routes
        - id: stats_route
          uri: lb://STATS-SERVER
          predicates:
            - Path=/stats/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG